name: pisigma-tal
version: 0.1.0.0
github: "ksrky/pisigma-tal"
license: BSD-3-Clause
author: "ksrk"
maintainer: "kswgrky@gmail.com"
copyright: "2023 ksrk"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ksrky/pisigma-tal#readme>

language: GHC2021

dependencies:
  - base >= 4.7 && < 5
  - containers
  - lens
  - megaparsec
  - mtl
  - parser-combinators
  - prettyprinter
  - recursion-schemes
  - text
  - transformers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - PatternSynonyms
  - TypeFamilies

library:
  source-dirs: src
  include-dirs:
    - src
  c-sources:
    - src/Tal/context.c
    - src/Tal/instruction.c
    - src/Tal/interpreter.c

tests:
  pisigma-tal-test:
    main: Tests.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pisigma-tal
      - bytestring
      - tasty
      - tasty-hunit
      - tasty-golden
